version: '3.3'

services:
  landing-data-search-console:
    build: .
    container_name: landing-data-search-console
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=landing-data-search-console"
      - "traefik.frontend.rule=Host:${SUBDOMAIN}"
      - "traefik.port=80"
      - "traefik.docker.network=web"
      # HTTPS/TLS Configuration
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  web:
    external: true
